name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Enable Flutter Web
      run: flutter config --enable-web

    - name: Install pub Dependencies
      run: flutter pub get

    - name: Install dependencies
      run: flutter packages get

    - name: Build web
      run: flutter build web -t lib/main.dart --pwa-strategy=none
      

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3 
      with:
        github_token: ${{ secrets.token }}
        publish_dir: ./build/web